import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeContextProvider } from "@/context/theme";
import ThemeWrapper from "@components/ThemeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeContextProvider>
      <ClerkProvider>
        <html lang="en">
          <body>
            <ThemeWrapper>{children}</ThemeWrapper>
          </body>
        </html>
      </ClerkProvider>
    </ThemeContextProvider>
  );
}
